export const SET_HEROES = 'SET_HEROES';
export const SET_ADD_MORE_HEROES = 'SET_ADD_MORE_HEROES';
export const SET_ISLOADING = 'SET_ISLOADING';
export const SET_HASERRORONLOADING = 'SET_HASERRORONLOADING';
