export const SET_HEROES = 'SET_HEROES';
export const SET_ADD_MORE_HEROES = 'SET_ADD_MORE_HEROES';
export const SET_SEARCH_HEROES = 'SET_SEARCH_HEROES';
export const SET_ADD_MORE_SEARCH_HEROES = 'SET_ADD_MORE_SEARCH_HEROES';
export const SET_RESET_SEARCH = 'SET_RESET_SEARCH';
export const SET_ISLOADING = 'SET_ISLOADING';
export const SET_HASERRORONLOADING = 'SET_HASERRORONLOADING';
