export const SET_EDIT_HERO = 'SET_EDIT_HERO';
export const SET_BATCH_EDIT_HERO = 'SET_BATCH_EDIT_HERO';
export const SET_REMOVE_EDIT_HERO = 'SET_REMOVE_EDIT_HERO';
export const SET_LOAD_MORE_SERIES = 'SET_LOAD_MORE_SERIES';